### ISSUE TITLE
.tag vs .badge

### ISSUE THREAD

**Issue by svrist** [Nodws/bootstrap4-tagsinput#1]
Shouldn't the default class be `.badge .badge-info` for `tagClass`  in 
https://github.com/Nodws/bootstrap4-tagsinput/blob/master/tagsinput.js#L11

given that `tag` is renamed in alpha6 of bootstrap? https://github.com/twbs/bootstrap/commit/d9fa3fd7971b5331b6582b46b568048458bb5544

**Comment by Nodws** [comment]
Yes in fact I did change it but only on my project, forgot to update it here asap :P
