### ISSUE TITLE
Typeahead does not work

### ISSUE THREAD

**Issue by mbaierl** [Nodws/bootstrap4-tagsinput#4]
Hi!
I am trying to build a tag input with typeahead and I am following your sample code:

```
$('#tags').tagsinput({
    typeahead: {
        source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']
    }
});
```

However it won't work, in the browser I receive this error message:

> jQuery.Deferred exception: self.$input.typeahead is not a function TypeError: self.$input.typeahead is not a function
>     at TagsInput.build (...)
>     at new TagsInput (...)
>     at HTMLInputElement.<anonymous> 

Any idea what I am doing wrong?

Thanks!

**Comment by Nodws** [comment]
typeahead function is not provided in the version of bootstrap you are using. Officially the typeahead is dropped from release 3.0. And is available separately in as typeahead.js.
Also[ jQuery must be included before typeahead.](https://stackoverflow.com/questions/38011594/typeerror-typeahead-is-not-a-function-even-including-typehead-js)

**Comment by Glideh** [comment]
Maybe this should be specified somewhere, I guessed typeahead was only working with Bootstrap 2 but I struggled a little bit to have a confirmation about it.
