### ISSUE TITLE
Add release and package.json

### ISSUE THREAD

**Issue by VirginieGarcin** [Nodws/bootstrap4-tagsinput#5]
Hello,

Would it be possible to add a file package.json at the root of the project and release tag to the current state?
So we could easily embed it in webjar (http://www.webjars.org/).

Thanks in advance for your feedback.

**Comment by Nodws** [comment]
Done and deployed to webjars.org, should be available in a few hours.

**Comment by VirginieGarcin** [comment]
Awesome, thank you!
